#!/usr/bin/env python
#-*- coding: utf8 -*-
'''
  Small program for quick access to SNS reflectometer raw data.
  Supports both the Magnetism Reflectometer (REF_M) and
  the Liquids Reflectometer (REF_L).
'''

import os
os.environ["QT_API"] = "pyqt5"
import sys
import argparse
import matplotlib
matplotlib.use("QtAgg")

# if script was run from commandline
try:
  if os.path.abspath(__file__).endswith('scripts/quicknxs'):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
except NameError:
  pass

# first thing to do is starting the logging system
from quicknxs.gui_logging import setup_system, check_runstate

def _run(argv=[], instrument='ref_m'):
  from qtpy.QtWidgets import QApplication, QSplashScreen
  from qtpy.QtGui import QPixmap
  from qtpy.QtCore import Qt
  app=QApplication(argv)
  from quicknxs import icons_rc, version  #@UnusedImport
  splash=QSplashScreen(QPixmap(u':/General/logo_hq.png'))
  #splash.setStyleSheet("qproperty-alignment: AlignBottom;")
  splash.showMessage(u"""<html>
                          <div style="margin-bottom: 420;"> &nbsp;</div>
                          <div style="font-size: 12pt; margin-bottom: 15;">
                            <b>QuickNXS</b> Version %s
                          </div>
                          <div>Starting up...</div>
                        </html>"""%version.str_version,
                     alignment=Qt.AlignBottom|Qt.AlignHCenter)
  splash.show()
  # set instrument configuration
  from quicknxs import config
  config.instrument=config.proxy.add_alias(instrument, 'instrument')

  from quicknxs.main_gui import MainGUI
  window=MainGUI(argv)
  window.show()
  splash.finish(window)
  return app.exec_()

if __name__=='__main__':
  parser=argparse.ArgumentParser(description='QuickNXS - SNS Reflectometer Data Reduction')
  parser.add_argument('--instrument', choices=['ref_m', 'ref_l'], default='ref_m',
                      help='Instrument to configure for (default: ref_m)')
  args, remaining=parser.parse_known_args()

  if check_runstate():
    # make sure the debug.log is not overwritten and only one version
    # of the program per user is running
    print("Another instance is already running")
    sys.exit(0)
  setup_system()
  if remaining and 'QuickNXS.app' in remaining[0]:
    remaining.pop(-1)
  sys.exit(_run(remaining, instrument=args.instrument))
